/*****************************************************************************
* Model: amulet_sensors.qm
* File:  ./amulet_sensors.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/3/0) .................................................................*/
#include <stdlib.h>

#include "amulet_sensors.h"



/* Active object class -----------------------------------------------------*/
/* @(/2/0) .................................................................*/
typedef struct AmuletSensorsTag {
/* protected: */
    QActive super;
} AmuletSensors;

/* protected: */
static QState AmuletSensors_initial(AmuletSensors * const me, QEvt const * const e);
static QState AmuletSensors_SensorsEnabled(AmuletSensors * const me, QEvt const * const e);



//void QF_onClockTick(void) {
//    QF_TICK((void *)0);
//}


/* Local objects -----------------------------------------------------------*/
static AmuletSensors l_amulet_sensors; /* the single instance of the AmuletSensors active object */


/* Global-scope objects ----------------------------------------------------*/
QActive * const AO_AmuletSensors = &l_amulet_sensors.super; /* "opaque" AO pointer */

/* @(/2/2) .................................................................*/
void AmuletSensors_ctor(void) {
    AmuletSensors *me = (AmuletSensors *)AO_AmuletSensors;
    QActive_ctor(&me->super, (QStateHandler)&AmuletSensors_initial);

}

/* @(/2/0) .................................................................*/
/* @(/2/0/0) ...............................................................*/
/* @(/2/0/0/0) */
static QState AmuletSensors_initial(AmuletSensors * const me, QEvt const * const e) {
    return Q_TRAN(&AmuletSensors_SensorsEnabled);
}
/* @(/2/0/0/1) .............................................................*/
static QState AmuletSensors_SensorsEnabled(AmuletSensors * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* @(/2/0/0/1/0) */
        case LIST_INTERNAL_SENSORS_SIG: {
            status_ = Q_TRAN(&AmuletSensors_SensorsEnabled);
            break;
        }
        /* @(/2/0/0/1/1) */
        case SUBSCRIBE_INTERNAL_SENSOR_SIG: {
            //uint8_t params[1] = {1};
            //uint8_t *params = malloc(2); //TODO: Make sure that you free
            //this memory after the correposnding IPC message has been
            //acked
            //params[0] = 0xfa;
            //params[1] = 0xce;
            //uint8_t sensor = Q_EVT_CAST(AmuletSensorsEvt)->sensor_id;
            //uint8_t caller = Q_EVT_CAST(AmuletSensorsEvt)->caller_id;
            //SubscribeInternalSensor(BUTTONA, params, 1, 0, 1, 0, 2);
            //SubscribeInternalSensor(sensor, params, 2, 0, 1, 0, caller);

            AmuletNetworkEvt *subscribeIPCMessageEvt;
            uint8_t * subscriptionParameters = malloc(11);

            //params
            //device_id, expiration, window_size, window_interval, caller_id
            //1+4+1+1+1
            //e.g.:
            //HRM, 0x0000, 0x0001,0x0001,0x01
            subscriptionParameters[0] = Q_EVT_CAST(AmuletSensorsEvt)->sensor_id;
            subscriptionParameters[1] = (uint8_t) Q_EVT_CAST(AmuletSensorsEvt)->expiration; //exp
            subscriptionParameters[2] = (uint8_t) (Q_EVT_CAST(AmuletSensorsEvt)->expiration) >> 8; //exp
            subscriptionParameters[3] = (uint8_t) Q_EVT_CAST(AmuletSensorsEvt)->window_size;
            subscriptionParameters[4] = (uint8_t) (Q_EVT_CAST(AmuletSensorsEvt)->window_size) >> 8;
            subscriptionParameters[5] = (uint8_t) Q_EVT_CAST(AmuletSensorsEvt)->window_interval;
            subscriptionParameters[6] = (uint8_t) (Q_EVT_CAST(AmuletSensorsEvt)->window_interval) >> 8;
            subscriptionParameters[7] = (uint8_t) Q_EVT_CAST(AmuletSensorsEvt)->imu_a;
            subscriptionParameters[8] = (uint8_t) Q_EVT_CAST(AmuletSensorsEvt)->imu_b;
            subscriptionParameters[9] = (uint8_t) Q_EVT_CAST(AmuletSensorsEvt)->imu_c;
            subscriptionParameters[10] = Q_EVT_CAST(AmuletSensorsEvt)->caller_id;


            subscribeIPCMessageEvt = Q_NEW(AmuletNetworkEvt, ADD_MESSAGE_TO_QUEUE_SIG);
            subscribeIPCMessageEvt->majorType = IPC_REQUEST;
            subscribeIPCMessageEvt->minorType = SUBSCRIBE_INTERNAL_SENSOR;
            subscribeIPCMessageEvt->targetID = INT_SENSOR_MAN_M0;
            subscribeIPCMessageEvt->params = subscriptionParameters;
            subscribeIPCMessageEvt->nparams = 11;

            SubscribeInternalSensor(Q_EVT_CAST(AmuletSensorsEvt)->sensor_id, subscriptionParameters, 11, 0, 1, 0, Q_EVT_CAST(AmuletSensorsEvt)->caller_id);
            QACTIVE_POST(AO_AmuletNetwork, &subscribeIPCMessageEvt->super, NULL);
            status_ = Q_TRAN(&AmuletSensors_SensorsEnabled);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

