/*****************************************************************************
* Model: amulet_ext_sensors.qm
* File:  ./amulet_ext_sensors.h
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/3/1) .................................................................*/
#ifndef amulet_ext_sensors_h
#define amulet_ext_sensors_h

#include "qp_port.h"
#include "amulet.h"
#include "amulet_api.h"


enum AmuletExternalSensorsSignals {
    FIND_SENSOR_SIG = Q_USER_SIG,
    SUBSCRIBE_EXT_SENSOR_SIG,
    EXT_DEVICE_DATA_SIG
};

//enum SensorSignals {
 //   BUTTON_A_PRESSED_SIG = Q_USER_SIG + 5,
  //  BUTTON_B_PRESSED_SIG
//};

/* @(/1/0) .................................................................*/
typedef struct ExternalSensorsEvtTag {
/* protected: */
    QEvt super;

/* public: */
    uint8_t sensor_id;
    uint8_t * data;
    uint16_t length;
    uint8_t sensor_type;
} ExternalSensorsEvt;

/* @(/1/1) .................................................................*/
typedef struct ExternalSensorsRequestEvtTag {
/* protected: */
    QEvt super;

/* public: */
    uint8_t device_id;
    uint16_t expiration;
    uint16_t window_size;
    uint16_t window_interval;
    uint8_t caller_id;
    uint8_t sensor_type;
} ExternalSensorsRequestEvt;


/* @(/2/2) .................................................................*/
void AmuletExternalSensors_ctor(void);

extern QActive * const AO_AmuletExternalSensors;


#endif                    /* amulet_ext_sensors_h */
