/*****************************************************************************
* Model: amulet_actuators.qm
* File:  ./amulet_actuators.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/3/0) .................................................................*/
#include <stdlib.h>
#include "amulet_actuators.h"

/* Active object class -----------------------------------------------------*/
/* @(/1/0) .................................................................*/
typedef struct AmuletActuatorsTag {
/* protected: */
    QActive super;
} AmuletActuators;

/* protected: */
static QState AmuletActuators_initial(AmuletActuators * const me, QEvt const * const e);
static QState AmuletActuators_ActuatorsEnabled(AmuletActuators * const me, QEvt const * const e);



//void QF_onClockTick(void) {
//    QF_TICK((void *)0);
//}


/* Local objects -----------------------------------------------------------*/
static AmuletActuators l_amulet_actuators; /* the single instance of the AmuletActuators active object */


/* Global-scope objects ----------------------------------------------------*/
QActive * const AO_AmuletActuators = &l_amulet_actuators.super; /* "opaque" AO pointer */

/* @(/1/2) .................................................................*/
void AmuletActuators_ctor(void) {
    AmuletActuators *me = (AmuletActuators *)AO_AmuletActuators;
    QActive_ctor(&me->super, (QStateHandler)&AmuletActuators_initial);

}

/* @(/1/0) .................................................................*/
/* @(/1/0/0) ...............................................................*/
/* @(/1/0/0/0) */
static QState AmuletActuators_initial(AmuletActuators * const me, QEvt const * const e) {
    //The lines below are not needed for directed messages
    //QActive_subscribe(&me->super, LEDON_SIG);
    //QActive_subscribe(&me->super, LEDOFF_SIG);
    return Q_TRAN(&AmuletActuators_ActuatorsEnabled);
}
/* @(/1/0/0/1) .............................................................*/
static QState AmuletActuators_ActuatorsEnabled(AmuletActuators * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* @(/1/0/0/1/0) */
        case LEDON_SIG: {
            //LedOn(Q_EVT_CAST(AmuletActuatorsEvt)->led_id);
            BSP_ledOn();

            /*
            const AmuletActuatorsEvt *reqEvt = Q_EVT_CAST(AmuletActuatorsEvt);

            uint8_t auth = reqEvt->authorization[0];


            if(3 == auth) {
                LedOn(Q_EVT_CAST(AmuletActuatorsEvt)->led_id);
                free(Q_EVT_CAST(AmuletActuatorsEvt)->authorization);
            } else {

                //reqEvt->super->sig = AUTHORIZATION_REQ_SIG;
                QACTIVE_POST(AO_AmuletAuthorization, &reqEvt->super,me);
            }
            */
            status_ = Q_TRAN(&AmuletActuators_ActuatorsEnabled);
            break;
        }
        /* @(/1/0/0/1/1) */
        case LEDOFF_SIG: {
            //LedOff(Q_EVT_CAST(AmuletActuatorsEvt)->led_id);
            BSP_ledOff();
            status_ = Q_TRAN(&AmuletActuators_ActuatorsEnabled);
            break;
        }
        /* @(/1/0/0/1/2) */
        case DISPLAY_MESSAGE_SIG: {
            /*
            uint8_t * recvmessage = Q_EVT_CAST(AmuletActuatorsEvt)->message;
            uint8_t recvlen = Q_EVT_CAST(AmuletActuatorsEvt)->message_len;
            DisplayMessage(recvmessage, recvlen);
            */
            //LedOn(ACTLED3);
            status_ = Q_TRAN(&AmuletActuators_ActuatorsEnabled);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

