/*****************************************************************************
* Model: amulet_ext_sensors.qm
* File:  ./amulet_ext_sensors.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/3/0) .................................................................*/
#include <stdlib.h>


#include "amulet_ext_sensors.h"


/* Active object class -----------------------------------------------------*/
/* @(/2/0) .................................................................*/
typedef struct AmuletExternalSensorsTag {
/* protected: */
    QActive super;
} AmuletExternalSensors;

/* protected: */
static QState AmuletExternalSensors_initial(AmuletExternalSensors * const me, QEvt const * const e);
static QState AmuletExternalSensors_ExternalSensorsEnabled(AmuletExternalSensors * const me, QEvt const * const e);



//void QF_onClockTick(void) {
//    QF_TICK((void *)0);
//}


/* Local objects -----------------------------------------------------------*/
static AmuletExternalSensors l_amulet_ext_sensors; /* the single instance of the AmuletExternalSensors active object */


/* Global-scope objects ----------------------------------------------------*/
QActive * const AO_AmuletExternalSensors = &l_amulet_ext_sensors.super; /* "opaque" AO pointer */

/* @(/2/2) .................................................................*/
void AmuletExternalSensors_ctor(void) {
    AmuletExternalSensors *me = (AmuletExternalSensors *)AO_AmuletExternalSensors;
    QActive_ctor(&me->super, (QStateHandler)&AmuletExternalSensors_initial);

}

/* @(/2/0) .................................................................*/
/* @(/2/0/0) ...............................................................*/
/* @(/2/0/0/0) */
static QState AmuletExternalSensors_initial(AmuletExternalSensors * const me, QEvt const * const e) {
    return Q_TRAN(&AmuletExternalSensors_ExternalSensorsEnabled);
}
/* @(/2/0/0/1) .............................................................*/
static QState AmuletExternalSensors_ExternalSensorsEnabled(AmuletExternalSensors * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* @(/2/0/0/1/0) */
        case FIND_SENSOR_SIG: {
            AmuletNetworkEvt *findDeviceIPCMessageEvt;
            uint8_t * messageParameters = malloc(1);

            //params
            //sensor_type
            messageParameters[0] = Q_EVT_CAST(ExternalSensorsRequestEvt)->sensor_type;

            findDeviceIPCMessageEvt = Q_NEW(AmuletNetworkEvt, ADD_MESSAGE_TO_QUEUE_SIG);
            findDeviceIPCMessageEvt->messageID = 550; //TODO:this needs to generated by the network manager
            findDeviceIPCMessageEvt->majorType = IPC_REQUEST;
            findDeviceIPCMessageEvt->minorType = FIND_SENSOR;
            findDeviceIPCMessageEvt->targetID = EXT_SENSOR_MAN_M0;
            findDeviceIPCMessageEvt->params = messageParameters;
            findDeviceIPCMessageEvt->nparams = 1;
            QACTIVE_POST(AO_AmuletNetwork, &findDeviceIPCMessageEvt->super, NULL);
            status_ = Q_TRAN(&AmuletExternalSensors_ExternalSensorsEnabled);
            break;
        }
        /* @(/2/0/0/1/1) */
        case SUBSCRIBE_EXT_SENSOR_SIG: {
            AmuletNetworkEvt *subscribeIPCMessageEvt;
            uint8_t * subscriptionParameters = malloc(8);

            //params
            //device_id, expiration, window_size, window_interval, caller_id
            //1+4+1+1+1
            //e.g.:
            //HRM, 0x0000, 0x0001,0x0001,0x01
            subscriptionParameters[0] = Q_EVT_CAST(ExternalSensorsRequestEvt)->device_id;
            subscriptionParameters[1] = (uint8_t) Q_EVT_CAST(ExternalSensorsRequestEvt)->expiration; //exp
            subscriptionParameters[2] = (uint8_t) (Q_EVT_CAST(ExternalSensorsRequestEvt)->expiration) >> 8; //exp
            subscriptionParameters[3] = (uint8_t) Q_EVT_CAST(ExternalSensorsRequestEvt)->window_size;
            subscriptionParameters[4] = (uint8_t) (Q_EVT_CAST(ExternalSensorsRequestEvt)->window_size) >> 8;
            subscriptionParameters[5] = (uint8_t) Q_EVT_CAST(ExternalSensorsRequestEvt)->window_interval;
            subscriptionParameters[6] = (uint8_t) (Q_EVT_CAST(ExternalSensorsRequestEvt)->window_interval) >> 8;
            subscriptionParameters[7] = Q_EVT_CAST(ExternalSensorsRequestEvt)->caller_id;


            subscribeIPCMessageEvt = Q_NEW(AmuletNetworkEvt, ADD_MESSAGE_TO_QUEUE_SIG);
            subscribeIPCMessageEvt->messageID = 500; //TODO:this needs to generated by the network manager
            subscribeIPCMessageEvt->majorType = IPC_REQUEST;
            subscribeIPCMessageEvt->minorType = SUBSCRIBE_EXTERNAL_SENSOR;
            subscribeIPCMessageEvt->targetID = EXT_SENSOR_MAN_M0;
            subscribeIPCMessageEvt->params = subscriptionParameters;
            subscribeIPCMessageEvt->nparams = 8;
            QACTIVE_POST(AO_AmuletNetwork, &subscribeIPCMessageEvt->super, NULL);
            status_ = Q_TRAN(&AmuletExternalSensors_ExternalSensorsEnabled);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

