/*****************************************************************************
* Model: amulet_authorization.qm
* File:  ./amulet_authorization.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/3/0) .................................................................*/
#include <stdlib.h>

#include "amulet_authorization.h"


/* Active object class -----------------------------------------------------*/
/* @(/2/0) .................................................................*/
typedef struct AmuletAuthorizationTag {
/* protected: */
    QActive super;

/* private: */
} AmuletAuthorization;
extern int8_t AmuletAuthorization_calls;
extern ipcMessage * AmuletAuthorization_outgoingQueue;

/* protected: */
static QState AmuletAuthorization_initial(AmuletAuthorization * const me, QEvt const * const e);
static QState AmuletAuthorization_NetworkEnabled(AmuletAuthorization * const me, QEvt const * const e);



/* Local objects -----------------------------------------------------------*/
static AmuletAuthorization l_amulet_authorization; /* the single instance of the AmuletAuthorization active object */


/* Global-scope objects ----------------------------------------------------*/
QActive * const AO_AmuletAuthorization = &l_amulet_authorization.super; /* "opaque" AO pointer */


/* @(/2/2) .................................................................*/
void AmuletAuthorization_ctor(void) {
    AmuletAuthorization *me = (AmuletAuthorization *)AO_AmuletAuthorization;
    QActive_ctor(&me->super, (QStateHandler)&AmuletAuthorization_initial);
    //QTimeEvt_ctor(&me->processNextEvt, SEND_MESSAGE_FROM_QUEUE_SIG);

}

/* @(/2/0) .................................................................*/
int8_t AmuletAuthorization_calls;
ipcMessage * AmuletAuthorization_outgoingQueue;
/* @(/2/0/2) ...............................................................*/
/* @(/2/0/2/0) */
static QState AmuletAuthorization_initial(AmuletAuthorization * const me, QEvt const * const e) {
    return Q_TRAN(&AmuletAuthorization_NetworkEnabled);
}
/* @(/2/0/2/1) .............................................................*/
static QState AmuletAuthorization_NetworkEnabled(AmuletAuthorization * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* @(/2/0/2/1/0) */
        case LEDON_SIG: {

            const AmuletActuatorsEvt *reqEvt = Q_EVT_CAST(AmuletActuatorsEvt);
            reqEvt->authorization[0] = 3;

            authorize();

            QACTIVE_POST(AO_AmuletActuators, &reqEvt->super,me);
            status_ = Q_TRAN(&AmuletAuthorization_NetworkEnabled);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

