/*****************************************************************************
* Model: blinky.qm
* File:  ..//blinky.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/2/0) .................................................................*/

#include "blinky.h"

/**
* Simple application that demonstrates how to blink an LED
* that is managed by the amulet
*/

/* Active object class -----------------------------------------------------*/
/* @(/1/0) .................................................................*/
typedef struct BlinkyTag {
/* protected: */
    QActive super;

/* private: */
    QTimeEvt timeEvt;
} Blinky;

/* protected: */
static QState Blinky_initial(Blinky * const me, QEvt const * const e);
static QState Blinky_off(Blinky * const me, QEvt const * const e);
static QState Blinky_on(Blinky * const me, QEvt const * const e);


//void QF_onClockTick(void) {
//   QF_TICK((void *)0);
//}


/* Local objects -----------------------------------------------------------*/
static Blinky l_blinky; /* the single instance of the Table active object */


/* Global-scope objects ----------------------------------------------------*/
QActive * const AO_Blinky = &l_blinky.super; /* "opaque" AO pointer */

/* @(/1/2) .................................................................*/
void Blinky_ctor(void) {
    Blinky *me = (Blinky *)AO_Blinky;
        QActive_ctor(&me->super, (QStateHandler)&Blinky_initial);
        QTimeEvt_ctor(&me->timeEvt, SWITCH_SIG);
}

/* @(/1/0) .................................................................*/
/* @(/1/0/1) ...............................................................*/
/* @(/1/0/1/0) */
static QState Blinky_initial(Blinky * const me, QEvt const * const e) {
    /*this is a comment*/
    QTimeEvt_postEvery(&me->timeEvt, (QActive *)me, BSP_TICKS_PER_SEC/2);
    return Q_TRAN(&Blinky_off);
}
/* @(/1/0/1/1) .............................................................*/
static QState Blinky_off(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* @(/1/0/1/1) */
        case Q_ENTRY_SIG: {
            //DIRECTED Message
            AmuletActuatorsEvt *ledEvt;

            ledEvt = Q_NEW(AmuletActuatorsEvt, LEDOFF_SIG);
            ledEvt->led_id =  ACTLED3;
            QACTIVE_POST(AO_AmuletActuators, &ledEvt->super, me);

            ///Do not call the BSP directly:
            //BSP_ledOff();

            ///Publish-subscribe message:
            //AmuletActuatorsEvt *ledEvt;
            //ledEvt = Q_NEW(AmuletActuatorsEvt, LEDOFF_SIG);
            //QF_PUBLISH(&ledEvt->super, me);

            status_ = Q_HANDLED();
            break;
        }
        /* @(/1/0/1/1/0) */
        case SWITCH_SIG: {
            status_ = Q_TRAN(&Blinky_on);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/* @(/1/0/1/2) .............................................................*/
static QState Blinky_on(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* @(/1/0/1/2) */
        case Q_ENTRY_SIG: {
            //DIRECTED message:
            AmuletActuatorsEvt *ledEvt;

            ledEvt = Q_NEW(AmuletActuatorsEvt, LEDON_SIG);
            ledEvt->led_id =  ACTLED3;
            QACTIVE_POST(AO_AmuletActuators ,&ledEvt->super, me);

            ///Do not call the BSP directly:
            //BSP_ledOn();

            ///Publish-subscribe message:
            ///AmuletActuatorsEvt *ledEvt;
            ///ledEvt = Q_NEW(AmuletActuatorsEvt, LEDON_SIG);
            ///QF_PUBLISH(&ledEvt->super, me);


            status_ = Q_HANDLED();
            break;
        }
        /* @(/1/0/1/2/0) */
        case SWITCH_SIG: {
            status_ = Q_TRAN(&Blinky_off);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

