/*****************************************************************************
* Model: requests_demo.qm
* File:  ..//requests_demo.h
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/2/1) .................................................................*/
#ifndef requests_demo_h
#define requests_demo_h


#include "qp_port.h"
#include "amulet_api.h"

enum RequestsDemoSignals {
    REQ_CHANGE_SIG = Q_USER_SIG,
};

/* @(/1/2) .................................................................*/
void RequestsDemo_ctor(void);

extern QActive * const AO_RequestsDemo;


#endif                    /* requests_demo_h */
