/*****************************************************************************
* Model: amulet_network.qm
* File:  ./amulet_network.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/3/0) .................................................................*/
#include "qp_port.h"
#include "amulet_network.h"
#include "bsp.h"

/* Active object class -----------------------------------------------------*/
/* @(/2/0) .................................................................*/
typedef struct AmuletNetworkTag {
/* protected: */
    QActive super;
} AmuletNetwork;

/* protected: */
static QState AmuletNetwork_initial(AmuletNetwork * const me, QEvt const * const e);
static QState AmuletNetwork_NetworkEnabled(AmuletNetwork * const me, QEvt const * const e);



//void QF_onClockTick(void) {
//    QF_TICK((void *)0);
//}


/* Local objects -----------------------------------------------------------*/
static AmuletNetwork l_amulet_network; /* the single instance of the AmuletNetwork active object */


/* Global-scope objects ----------------------------------------------------*/
QActive * const AO_AmuletNetwork = &l_amulet_network.super; /* "opaque" AO pointer */

/* @(/2/2) .................................................................*/
void AmuletNetwork_ctor(void) {
    AmuletNetwork *me = (AmuletNetwork *)AO_AmuletNetwork;
    QActive_ctor(&me->super, (QStateHandler)&AmuletNetwork_initial);

}

/* @(/2/0) .................................................................*/
/* @(/2/0/0) ...............................................................*/
/* @(/2/0/0/0) */
static QState AmuletNetwork_initial(AmuletNetwork * const me, QEvt const * const e) {
    return Q_TRAN(&AmuletNetwork_NetworkEnabled);
}
/* @(/2/0/0/1) .............................................................*/
static QState AmuletNetwork_NetworkEnabled(AmuletNetwork * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* @(/2/0/0/1/0) */
        case LIST_DEVICES_SIG: {
            status_ = Q_TRAN(&AmuletNetwork_NetworkEnabled);
            break;
        }
        /* @(/2/0/0/1/1) */
        case FIND_DEVICE_SIG: {
            status_ = Q_TRAN(&AmuletNetwork_NetworkEnabled);
            break;
        }
        /* @(/2/0/0/1/2) */
        case CONFIG_DEVICE_SIG: {
            status_ = Q_TRAN(&AmuletNetwork_NetworkEnabled);
            break;
        }
        /* @(/2/0/0/1/3) */
        case SUBS_DEVICE_SIG: {
            status_ = Q_TRAN(&AmuletNetwork_NetworkEnabled);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

