/*****************************************************************************
* Model: amulet.qm
* File:  ./amulet.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/3/0) .................................................................*/
#include "qp_port.h"
#include "dpp.h"
#include "blinky.h"
#include "amulet.h"
#include "bsp.h"

/* Active object class -----------------------------------------------------*/
/* @(/1/0) .................................................................*/
typedef struct AmuletTag {
/* protected: */
    QActive super;

/* public: */
    QTimeEvt timeEvt;
} Amulet;

/* protected: */
static QState Amulet_initial(Amulet * const me, QEvt const * const e);
static QState Amulet_ServicesEnabled(Amulet * const me, QEvt const * const e);



//void QF_onClockTick(void) {
//    QF_TICK((void *)0);
//}


/* Local objects -----------------------------------------------------------*/
static Amulet l_amulet; /* the single instance of the Amulet active object */


/* Global-scope objects ----------------------------------------------------*/
QActive * const AO_Amulet = &l_amulet.super; /* "opaque" AO pointer */

/* @(/1/2) .................................................................*/
void Amulet_ctor(void) {
    Amulet *me = (Amulet *)AO_Amulet;
        QActive_ctor(&me->super, (QStateHandler)&Amulet_initial);
        //QTimeEvt_ctor(&me->timeEvt, TSWITCH_SIG);
}

/* @(/1/0) .................................................................*/
/* @(/1/0/1) ...............................................................*/
/* @(/1/0/1/0) */
static QState Amulet_initial(Amulet * const me, QEvt const * const e) {
    /*this is a comment*/
    //QTimeEvt_postEvery(&me->timeEvt, (QActive *)me, BSP_TICKS_PER_SEC/2);
    //QActive_subscribe(&me->super, DONE_SIG);
    //QActive_subscribe(&me->super, PAUSE_SIG);
    QActive_subscribe(&me->super, TURNLEDON_SIG);
    QActive_subscribe(&me->super, TURNLEDOFF_SIG);
    return Q_TRAN(&Amulet_ServicesEnabled);
}
/* @(/1/0/1/1) .............................................................*/
static QState Amulet_ServicesEnabled(Amulet * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* @(/1/0/1/1) */
        case Q_ENTRY_SIG: {
            //BSP_ConfigureServices();
            status_ = Q_HANDLED();
            break;
        }
        /* @(/1/0/1/1/0) */
        case TURNLEDON_SIG: {
            BSP_ledOn();
            //BSP_temperatureOn();
            status_ = Q_TRAN(&Amulet_ServicesEnabled);
            break;
        }
        /* @(/1/0/1/1/1) */
        case TURNLEDOFF_SIG: {
            BSP_ledOff();
            status_ = Q_TRAN(&Amulet_ServicesEnabled);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

