/*****************************************************************************
* Model: amulet_actuators.qm
* File:  ./amulet_actuators.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/3/0) .................................................................*/
#include "qp_port.h"
#include "dpp.h"
#include "blinky.h"
#include "amulet_actuators.h"
#include "bsp.h"

/* Active object class -----------------------------------------------------*/
/* @(/1/0) .................................................................*/
typedef struct AmuletActuatorsTag {
/* protected: */
    QActive super;
} AmuletActuators;

/* protected: */
static QState AmuletActuators_initial(AmuletActuators * const me, QEvt const * const e);
static QState AmuletActuators_ActuatorsEnabled(AmuletActuators * const me, QEvt const * const e);



//void QF_onClockTick(void) {
//    QF_TICK((void *)0);
//}


/* Local objects -----------------------------------------------------------*/
static AmuletActuators l_amulet_actuators; /* the single instance of the AmuletActuators active object */


/* Global-scope objects ----------------------------------------------------*/
QActive * const AO_AmuletActuators = &l_amulet_actuators.super; /* "opaque" AO pointer */

/* @(/1/2) .................................................................*/
void AmuletActuators_ctor(void) {
    AmuletActuators *me = (AmuletActuators *)AO_AmuletActuators;
    QActive_ctor(&me->super, (QStateHandler)&AmuletActuators_initial);

}

/* @(/1/0) .................................................................*/
/* @(/1/0/0) ...............................................................*/
/* @(/1/0/0/0) */
static QState AmuletActuators_initial(AmuletActuators * const me, QEvt const * const e) {
    return Q_TRAN(&AmuletActuators_ActuatorsEnabled);
}
/* @(/1/0/0/1) .............................................................*/
static QState AmuletActuators_ActuatorsEnabled(AmuletActuators * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* @(/1/0/0/1/0) */
        case LEDON_SIG: {
            BSP_ledOn();
            status_ = Q_TRAN(&AmuletActuators_ActuatorsEnabled);
            break;
        }
        /* @(/1/0/0/1/1) */
        case LEDOFF_SIG: {
            BSP_ledOff();
            status_ = Q_TRAN(&AmuletActuators_ActuatorsEnabled);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

