/*****************************************************************************
* Model: amulet_sensors.qm
* File:  ./amulet_sensors.h
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/3/1) .................................................................*/
#ifndef amulet_sensors_h
#define amulet_sensors_h


enum AmuletSensorsSignals {
    ENABLE_TEMP_SENSOR_SIG = Q_USER_SIG,
    DISABLE_TEMP_SENSOR_SIG,
    GET_TEMPERATURE_SIG,
    ENABLE_LIGHT_SENSOR_SIG,
    DISABLE_LIGHT_SENSOR_SIG,
    GET_LIGHT_SENSOR_SIG,
    ENABLE_MPU_SIG,
    DISABLE_MPU_SIG,
    CONFIG_MPU_SIG,
    SUBS_MPU_ACCEL_SIG,
    SUBS_MPU_GYRO_SIG,
    SUBS_MPU_MAGNET_SIG,
    SUBS_BUTTON_SIG,
    UNSUBS_BUTTON_SIG
};

/* @(/1/0) .................................................................*/
typedef struct AmuletSensorsEvtTag {
/* protected: */
    QEvt super;

/* public: */
    uint8_t mpu_filter;
    uint8_t mpu_range;
    uint8_t mpu_freq;
    uint32_t subs_expiration;
    uint8_t subs_window_size;
    uint8_t button_id;
} AmuletSensorsEvt;


/* @(/2/2) .................................................................*/
void AmuletSensors_ctor(void);

extern QActive * const AO_AmuletSensors;


#endif                    /* amulet_sensors_h */
