/*****************************************************************************
* Model: amulet_network.qm
* File:  ./amulet_network.h
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/3/1) .................................................................*/
#ifndef amulet_network_h
#define amulet_network_h


enum AmuletNetworkSignals {
    LIST_DEVICES_SIG = Q_USER_SIG,
    FIND_DEVICE_SIG,
    CONFIG_DEVICE_SIG,
    SUBS_DEVICE_SIG,
};

/* @(/1/0) .................................................................*/
typedef struct AmuletNetworkEvtTag {
/* protected: */
    QEvt super;

/* public: */
    uint16_t device_id;
    uint32_t subs_expiration;
    uint8_t subs_window_size;

    // This will actually have to be changed by a class
    uint16_t params;
} AmuletNetworkEvt;


/* @(/2/2) .................................................................*/
void AmuletNetwork_ctor(void);

extern QActive * const AO_AmuletNetwork;


#endif                    /* amulet_network_h */
