/*****************************************************************************
* Model: amulet_sensors.qm
* File:  ./amulet_sensors.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/3/0) .................................................................*/
#include "qp_port.h"
#include "amulet_sensors.h"
#include "bsp.h"

/* Active object class -----------------------------------------------------*/
/* @(/2/0) .................................................................*/
typedef struct AmuletSensorsTag {
/* protected: */
    QActive super;
} AmuletSensors;

/* protected: */
static QState AmuletSensors_initial(AmuletSensors * const me, QEvt const * const e);
static QState AmuletSensors_SensorsEnabled(AmuletSensors * const me, QEvt const * const e);



//void QF_onClockTick(void) {
//    QF_TICK((void *)0);
//}


/* Local objects -----------------------------------------------------------*/
static AmuletSensors l_amulet_sensors; /* the single instance of the AmuletSensors active object */


/* Global-scope objects ----------------------------------------------------*/
QActive * const AO_AmuletSensors = &l_amulet_sensors.super; /* "opaque" AO pointer */

/* @(/2/2) .................................................................*/
void AmuletSensors_ctor(void) {
    AmuletSensors *me = (AmuletSensors *)AO_AmuletSensors;
    QActive_ctor(&me->super, (QStateHandler)&AmuletSensors_initial);

}

/* @(/2/0) .................................................................*/
/* @(/2/0/0) ...............................................................*/
/* @(/2/0/0/0) */
static QState AmuletSensors_initial(AmuletSensors * const me, QEvt const * const e) {
    return Q_TRAN(&AmuletSensors_SensorsEnabled);
}
/* @(/2/0/0/1) .............................................................*/
static QState AmuletSensors_SensorsEnabled(AmuletSensors * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* @(/2/0/0/1/0) */
        case ENABLE_TEMP_SENSOR_SIG: {
            status_ = Q_TRAN(&AmuletSensors_SensorsEnabled);
            break;
        }
        /* @(/2/0/0/1/1) */
        case DISABLE_TEMP_SENSOR_SIG: {
            status_ = Q_TRAN(&AmuletSensors_SensorsEnabled);
            break;
        }
        /* @(/2/0/0/1/2) */
        case GET_TEMPERATURE_SIG: {
            status_ = Q_TRAN(&AmuletSensors_SensorsEnabled);
            break;
        }
        /* @(/2/0/0/1/3) */
        case ENABLE_LIGHT_SENSOR_SIG: {
            status_ = Q_TRAN(&AmuletSensors_SensorsEnabled);
            break;
        }
        /* @(/2/0/0/1/4) */
        case DISABLE_LIGHT_SENSOR_SIG: {
            status_ = Q_TRAN(&AmuletSensors_SensorsEnabled);
            break;
        }
        /* @(/2/0/0/1/5) */
        case GET_LIGHT_SENSOR_SIG: {
            status_ = Q_TRAN(&AmuletSensors_SensorsEnabled);
            break;
        }
        /* @(/2/0/0/1/6) */
        case ENABLE_MPU_SIG: {
            status_ = Q_TRAN(&AmuletSensors_SensorsEnabled);
            break;
        }
        /* @(/2/0/0/1/7) */
        case DISABLE_MPU_SIG: {
            status_ = Q_TRAN(&AmuletSensors_SensorsEnabled);
            break;
        }
        /* @(/2/0/0/1/8) */
        case CONFIG_MPU_SIG: {
            status_ = Q_TRAN(&AmuletSensors_SensorsEnabled);
            break;
        }
        /* @(/2/0/0/1/9) */
        case SUBS_MPU_ACCEL_SIG: {
            status_ = Q_TRAN(&AmuletSensors_SensorsEnabled);
            break;
        }
        /* @(/2/0/0/1/10) */
        case SUBS_MPU_GYRO_SIG: {
            status_ = Q_TRAN(&AmuletSensors_SensorsEnabled);
            break;
        }
        /* @(/2/0/0/1/11) */
        case SUBS_MPU_MAGNET_SIG: {
            status_ = Q_TRAN(&AmuletSensors_SensorsEnabled);
            break;
        }
        /* @(/2/0/0/1/12) */
        case SUBS_BUTTON_SIG: {
            status_ = Q_TRAN(&AmuletSensors_SensorsEnabled);
            break;
        }
        /* @(/2/0/0/1/13) */
        case UNSUBS_BUTTON_SIG: {
            status_ = Q_TRAN(&AmuletSensors_SensorsEnabled);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

